### ISSUE TITLE
Inconsistency between Permute and Etumrep

### ISSUE THREAD

**Issue by 0757myt** [kwsch/PermuteMMO#12]
Seed from PermuteMMO is wrong on two cases, both on a Dartrix MMO. I don't have the file from the first incident anymore but I have this one:
Permute 1.3.2 shows Shiny on 4th spawn with the seed 8825218332048646920, but the shiny wasn't there in-game.
![033](https://github.com/kwsch/PermuteMMO/assets/133282841/3c3969c2-f70e-4111-abb7-1b40eb73b084)
[mmo and main.zip](https://github.com/kwsch/PermuteMMO/files/12582156/mmo.and.main.zip)

After catching the first 4, I ran the pa8 in Etumrep 1.1.1 and got a different seed (this time is correct): 10279198074322915649
Which gave me the following, where an A4 is needed
![154](https://github.com/kwsch/PermuteMMO/assets/133282841/3e1f64f0-9889-436b-810c-d10932c768f7)
[mons.zip](https://github.com/kwsch/PermuteMMO/files/12582200/mons.zip)
Encounter table is 0x65503545DDDA60FA , species 723

**Comment by kwsch** [comment]
No idea; gonna close due to nobody investigating.

Only thoughts for if this happens again -- notes for any future issues(idk lol):
* Check TID/SID for shininess and reroll counts
* Might be a multi-seed solution (many seeds can explain the inputs)

Generally, the guidance for permutation oddities is "just ignore it and try a different outbreak".

**Comment by BalletDuckNinja** [comment]
commenting here because I'm noticing permuteMMO also not giving me correct results if I have read my entire 'main' save directly. Etumrep gave me a different seed for the same MMO, when entered into permuteMMO it gave me a working path to a shiny.

**Comment by BalletDuckNinja** [comment]
![permmo reverse vs save](https://github.com/user-attachments/assets/cba51db8-3edc-42af-b090-7f11ecacc716)

Adding a comparison between the correct seed obtained from Etumrep (top) and the seed obtained from PermuteMMO (bottom). The shiny it predicts in both cases is the same.
